version: '3.9'
services:
  db:
    image: postgres
    container_name: portfly-postgresql-server
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root123
      - POSTGRES_DB=portfly
  adminer:
    image: adminer
    container_name: portfly-adminer
    restart: always
    ports:
      - 8080:8080
  redis:
    image: redis
    container_name: portfly-redis-server
    restart: always
    ports:
      - 6379:6379
