version: '3.9'
services:
  db:
    image: postgres
    container_name: portfly-postgresql
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root123
      - POSTGRES_DB=portfly
  redis:
    image: redis
    container_name: portfly-redis
    restart: always
    ports:
      - 6379:6379
